/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  AbstractRoyalties,
  AbstractRoyaltiesInterface,
} from "../AbstractRoyalties";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x49a66134",
        type: "bytes32",
      },
    ],
    name: "c_0x49a66134",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

export class AbstractRoyalties__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractRoyaltiesInterface {
    return new utils.Interface(_abi) as AbstractRoyaltiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractRoyalties {
    return new Contract(address, _abi, signerOrProvider) as AbstractRoyalties;
  }
}
