on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Compile and test code
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run compile
      - run: npm run lint:sol
